### ISSUE TITLE
while running the app it kept showing this error and after getting all dependencies again and again it shows 'Pakage get' has not been run

### ISSUE THREAD

**Issue by YASH18052000** [londonappbrewery/MiCard-Completed#3]
Launching lib\main.dart on POCO F1 in debug mode...
Running Gradle task 'assembleDebug'...
Exception in thread "main" java.net.UnknownHostException: services.gradle.org
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
	at org.gradle.wrapper.Download.download(Download.java:44)
	at org.gradle.wrapper.Install$1.call(Install.java:61)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Finished with error: Gradle task assembleDebug failed with exit code 1
![Screenshot (3)](https://user-images.githubusercontent.com/61594170/77173496-9a7a9000-6ae5-11ea-8e04-93efa72f7d52.png)
![Screenshot (4)](https://user-images.githubusercontent.com/61594170/77173517-9d758080-6ae5-11ea-9f3c-a506f8d07a15.png)

**Comment by sad-adnan** [comment]
I also faced the same problem, please check if you have internet connection or not, the first time you build your app, it will download gradle files and other data, so you will need internet connection (It will download at least 150MB), AFTER this your app will run, and than if you don't change gradle version or dependencies this is solved and your project will be run, similarly after download, run flutter app from command prompt using flutter run -v and it will run showing all the steps , i hope it solves the issue.

**Comment by roshanshilpakar** [comment]
once check all the dependencies and update all the packages of application. Also make the formatting of the text in the IDE properly. also please send us the code so that we can send you the solutions.
